name: 'luast'
description: 'Build standalone Lua binaries with cross-compilation support'
author: 'pgagnidze'

branding:
  icon: 'package'
  color: 'blue'

inputs:
  output:
    description: 'Output binary name (default: package name from rockspec or main filename)'
    required: false
  main:
    description: 'Main entry point for standalone mode (no rockspec needed)'
    required: false
  rockspec:
    description: 'Path to rockspec file (default: auto-detect)'
    required: false
  targets:
    description: 'Space-separated list of targets (e.g., "linux-x86_64 linux-arm64 darwin-arm64 windows-x86_64")'
    required: false
  lua-version:
    description: 'Lua version to use (default: 5.4.8, or "jit" for LuaJIT)'
    required: false
  clibs:
    description: 'Space-separated list of C library dependencies (e.g., "lfs lpeg")'
    required: false
  rocks:
    description: 'Space-separated list of LuaRocks packages to include (e.g., "inspect penlight")'
    required: false
  embeds:
    description: 'Space-separated list of files/directories to embed (e.g., "templates/ config.json")'
    required: false
  quiet:
    description: 'Only show errors and warnings (default: false)'
    required: false
    default: 'false'

outputs:
  binary:
    description: 'Path to the built binary (or first binary if multiple targets)'
    value: ${{ steps.build.outputs.binary }}

runs:
  using: 'composite'
  steps:
    - name: Cache luast dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/luast
        key: luast-${{ runner.os }}

    - name: Install Lua (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y lua5.4 liblua5.4-dev

    - name: Install Lua (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: brew install lua

    - name: Build binary
      id: build
      shell: bash
      run: |
        LUAST_SCRIPT="${{ github.action_path }}/luast"

        if [ -n "${{ inputs.lua-version }}" ]; then
          export LUA_VERSION="${{ inputs.lua-version }}"
        fi

        ARGS=""

        if [ "${{ inputs.quiet }}" = "true" ]; then
          ARGS="$ARGS -q"
        fi

        if [ -n "${{ inputs.main }}" ]; then
          ARGS="$ARGS -m ${{ inputs.main }}"
        fi

        if [ -n "${{ inputs.rockspec }}" ]; then
          ARGS="$ARGS -r ${{ inputs.rockspec }}"
        fi

        if [ -n "${{ inputs.targets }}" ]; then
          for target in ${{ inputs.targets }}; do
            ARGS="$ARGS -t $target"
          done
        fi

        if [ -n "${{ inputs.clibs }}" ]; then
          for clib in ${{ inputs.clibs }}; do
            ARGS="$ARGS -c $clib"
          done
        fi

        if [ -n "${{ inputs.rocks }}" ]; then
          for rock in ${{ inputs.rocks }}; do
            ARGS="$ARGS -R $rock"
          done
        fi

        if [ -n "${{ inputs.embeds }}" ]; then
          for embed in ${{ inputs.embeds }}; do
            ARGS="$ARGS -e $embed"
          done
        fi

        if [ -n "${{ inputs.output }}" ]; then
          ARGS="$ARGS ${{ inputs.output }}"
        fi

        "$LUAST_SCRIPT" $ARGS

        OUTPUT="${{ inputs.output }}"
        if [ -z "$OUTPUT" ]; then
          if [ -n "${{ inputs.main }}" ]; then
            OUTPUT=$(basename "${{ inputs.main }}" .lua)
          else
            OUTPUT=$(ls *.rockspec 2>/dev/null | head -1 | sed 's/-.*$//' || echo "output")
          fi
        fi

        echo "binary=$OUTPUT" >> $GITHUB_OUTPUT
